### PR TITLE
replace sync-exec with spawn-sync

### LINKED ISSUE #1: GPL dependency
Continuing [from twitter](https://twitter.com/rmgraham/status/620696391753412608)..

@sindresorhus would you accept a PR that replaced sync-exec with https://github.com/ForbesLindesay/spawn-sync ?

**edit** for posterity, this is related to gvarsanyi/sync-exec#10

### PR DESCRIPTION
**Pull request by rmg**
Addresses a minor concern about GPL'd dependencies.

Resolves #1

### CODE REVIEW

**Comment by sindresorhus** [comment]
You can't just switch them out. They accept different input and works differently.

**Comment by rmg** [comment]
@sindresorhus ya, I noticed that after looking at the Travis failure.. I use iojs locally, so when I ran `npm test` it didn't even touch the changed code. I've force pushed a change.. it makes the module look like it might not even be necessary..

**Comment by rmg** [comment]
...Not necessary for simple cases, I mean.

**Comment by rmg** [comment]
Alternatively, could use the actual implementation of execFileSync from v0.12: https://github.com/joyent/node/blob/6036e4f5a833b27fb474f3bf891c405606fdce19/lib/child_process.js#L1359-L1375 since it's not exactly complicated...

``` js
function checkExecSyncError(ret) {
  if (ret.error || ret.status !== 0) {
    var err = ret.error;
    ret.error = null;

    if (!err) {
      var msg = 'Command failed: ' +
                (ret.cmd ? ret.cmd : ret.args.join(' ')) +
                (ret.stderr ? '\n' + ret.stderr.toString() : '');
      err = new Error(msg);
    }

    util._extend(err, ret);
    return err;
  }

  return false;
}

function execFileSync(/*command, options*/) {
  var opts = normalizeSpawnArguments.apply(null, arguments);
  var inheritStderr = !opts.options.stdio;

  var ret = spawnSync(opts.file, opts.args.slice(1), opts.options);

  if (inheritStderr)
    process.stderr.write(ret.stderr);

  var err = checkExecSyncError(ret);

  if (err)
    throw err;
  else
    return ret.stdout;
}
exports.execFileSync = execFileSync;
```

**Comment by sindresorhus** [comment]
> Alternatively, could use the actual implementation of execFileSync from v0.12:

:+1:

**Comment by rmg** [comment]
@sindresorhus there were a few more function dependencies than my previous comment indicated.. but I've copied in the version from core. The only difference is adding `isObject` to the module and changing 2 invocations of it instead of polyfilling `util`.

**Comment by rmg** [comment]
@sindresorhus plan to merge? Need more changes?

**Comment by kevva** [comment]
This feels rather extensive just to migrate away from GPL.

**Comment by rmg** [comment]
@kevva agreed, it did sort of morph into a complete rewrite of the module. The original PR was only a couple lines, and then a few more were added, and then after a couple comments a complete import from core. The final version actually feels (to me) like the most correct way to write this module, but it definitely goes _a lot_ further than originally intended.

But all that aside, this is _still_ simpler than the alternative: arguing with a lawyer and/or judge about how node's module system works w.r.t. the GPL.

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by sindresorhus** [comment]
I did a major release just in case this changed some behaviour.

**Comment by rmg** [comment]
> I did a major release just in case this changed some behaviour.

good call :+1:

**Comment by rmg** [comment]
@sindresorhus do you want the 1-line PR to update passwd-user to use exec-file-sync@2? Seems like it would probably be easier for you to do yourself since you'd want to cut a release after anyway..

**Comment by sindresorhus** [comment]
@rmg done https://github.com/sindresorhus/passwd-user/commit/81fd63ac1abb524e3c4cb03c18e7f0ea8097c740 :)

**Comment by rmg** [comment]
:tada:

**Pull request merged**
